set_property SRC_FILE_INFO {cfile:{/home/nicolas/Documentos/CESE 2021/Cursos/13. Microarquitecturas y softcores/Clase 5/lab3_ArtyZ7_10.xdc} rfile:{../../../../../CESE 2021/Cursos/13. Microarquitecturas y softcores/Clase 5/lab3_ArtyZ7_10.xdc} id:1} [current_design]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports LED_0[0]]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports LED_0[1]]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports LED_0[2]]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports LED_0[3]]
